function options = optimizerSetup(options)
% options = optimizerSetup(options)
% Display a dialog box with specific solver options and read the results

% Gather default options: [name,default,read-in type]
if isempty(options)
options = { 'Algorithm',                'interior-point',   'char';     ...
            'Display',                  'iter',             'char';     ...
            'FiniteDifferenceType',     'forward',          'char';     ...
            'HessianApproximation',     'bfgs',             'char';     ...
            'MaxFunctionEvaluations',   '1e6',              'numeric';  ...
            'MaxIterations',            '5e3',              'numeric';  ...
            'ObjectiveLimit',           '0',                'numeric';  ...
            'OptimalityTolerance',      '1e-6',             'numeric';  ...
            'StepTolerance',            '1e-7',             'numeric';  ...
            'SubproblemAlgorithm',      'factorization',    'char';     ...
            'OutputFcn',                '@ProgressPlot',    'symbolic'; ...
            'UseParallel',              'true',             'symbolic'};
else

% Create dialog box and display all relevant options
options(:,2)    = inputdlg(                                             ...
                        options(:,1),                                   ...
                        'Optimizer settings (fmincon)',                 ...
                        [1,50],                                         ...
                        options(:,2) );
end

                    


end